# Configurações referente ao Spring
services:

  loja:
    build: .
    image: eclipse-temurin:17-jdk-focal
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_USER_EMAIL=${USER_EMAIL}
      - SPRING_EMAIL_PASSWORD=${PASSWORD_USER}
      - TOKEN_MERCADO_PAGO=${TOKEN_MP}
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - uploads:/app/uploads

# Configurações referente ao MySQL
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  uploads:
